services:
  telegraf:
      image: telegraf:latest
      container_name: telegraf
      restart: always
      environment:
        - INFLUX_TOKEN=replaceMe
      volumes:
        - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      depends_on:
        - influxdb
      links:
        - influxdb
      ports:
      - '8125:8125'

  influxdb:
      image: influxdb:latest
      container_name: influxdb
      restart: always
      environment:
        - INFLUXDB_DB=influx
        - INFLUXDB_ADMIN_USER=admin
        - INFLUXDB_ADMIN_PASSWORD=admin
      ports:
        - '8086:8086'
      links:
        - grafana
      volumes:
        - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
        - influxdb
    links:
        - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data: {}
  influxdb_data: {}
